version: '3'
services:
  indexer:
    build: ../
    command: ./explorer -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - INDEXER_ENABLED=true
    network_mode: "host"
  eth1indexer:
    build: ../
    command: ./eth1indexer -config /app/config.yml -blocks.concurrency 1 -data.concurrency 1 --balances.enabled
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  frontend-data-updater:
    build: ../
    command: ./frontend-data-updater -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  frontend:
    build: ../
    command: ./explorer -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - FRONTEND_ENABLED=true
    network_mode: "host"